/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.companyname.view;

import com.companyname.dao.EmployeeDao;
import com.companyname.dto.Employee;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhaskar
 */
public class EmployeeForm extends javax.swing.JFrame {
    DefaultTableModel dtm; 
    public void showData(){
        List<Employee> employeeList=new EmployeeDao().getEmployeeList();
        DefaultTableModel tableModel=(DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0);
        for(Employee employee:employeeList){
            tableModel.addRow(new Object[]{employee.getId(),employee.getUsername(),employee.getPassword()});
        }
    }
    

    /**
     * Creates new form EmployeeForm
     */
    public EmployeeForm() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jpassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setMinimumSize(new java.awt.Dimension(472, 381));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 50, 118, 32);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(190, 40, 164, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 90, 97, 24);

        insert.setBackground(new java.awt.Color(255, 102, 102));
        insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insert.setForeground(new java.awt.Color(0, 0, 255));
        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert);
        insert.setBounds(10, 140, 71, 35);

        Edit.setBackground(new java.awt.Color(255, 0, 0));
        Edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(0, 0, 204));
        Edit.setText("edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(130, 140, 65, 35);

        delete.setBackground(new java.awt.Color(255, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 204));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(250, 140, 75, 35);

        clear.setBackground(new java.awt.Color(255, 0, 0));
        clear.setForeground(new java.awt.Color(0, 0, 204));
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(370, 140, 65, 37);

        jTable2.setBackground(new java.awt.Color(51, 255, 255));
        jTable2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTable2.setForeground(new java.awt.Color(255, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "username", "password"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 173, 490, 130);
        getContentPane().add(jpassword);
        jpassword.setBounds(190, 87, 164, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 310, 77, 31);

        jLabel4.setBackground(new java.awt.Color(255, 102, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("EMPLOYEE FORM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 0, 290, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/companyname/view/lambhu.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 20, 470, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     int row=  jTable2.getSelectedRow();
        DefaultTableModel tableModel=(DefaultTableModel) jTable2.getModel();
        Object employeeId=tableModel.getValueAt(row, 0);
        new EmployeeDao().deleteEmployeeInfo(Integer.parseInt(employeeId.toString()));
        username.setText("");  
jpassword.setText("");
        showData();
        
// TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
          
        Employee employee=new Employee();
//        employee.setType((String)select1.getSelectedItem());
        employee.setUsername(username.getText());
        employee.setPassword(jpassword.getText());
        EmployeeDao dao=new EmployeeDao();
        dao.saveEmployeeInfo(employee);
        JOptionPane.showMessageDialog(null, "saved successfully");
        username.setText("");
        jpassword.setText("");
        showData();

        // TODO add your handling code here:
    }//GEN-LAST:event_insertActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
 int row=  jTable2.getSelectedRow();
        DefaultTableModel tableModel=(DefaultTableModel) jTable2.getModel();
        Object employeeId=tableModel.getValueAt(row, 0);
//        Object select1=tableModel.getValueAt(row,1);
        Object name=tableModel.getValueAt(row,1 );
        Object password=tableModel.getValueAt(row,2);
         
        EmployeeEditForm editForm=new EmployeeEditForm();
        editForm.id.setText(employeeId.toString());
   editForm.username1.setText(name.toString());
   editForm.jpassword.setText(password.toString());
   this.dispose();
   editForm.setVisible(true);
   
   
   
   
   
 
        
 

        
// TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
username.setText("");  
jpassword.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       int isrowselected = jTable2.getSelectedRowCount();
        
        if (isrowselected==1) {
                 
        
        
         int row=  jTable2.getSelectedRow();
        DefaultTableModel tableModel=(DefaultTableModel) jTable2.getModel();
Object employeeId=tableModel.getValueAt(row, 0).toString();
//select1.getSelectedItem();
username.setText(tableModel.getValueAt(row,1).toString());
jpassword.setText(tableModel.getValueAt(row,2).toString());


        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
AdminMenuset g= new AdminMenuset();
g.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Edit;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    public javax.swing.JPasswordField jpassword;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
