/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.companyname.view;

import com.companyname.dao.FullBillingsDao;

import com.companyname.database.Database;
import com.companyname.dto.Bill;
import com.companyname.dto.Employee;
import static com.companyname.view.FullBillings.convert_CM_TO_PPI;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.geom.Rectangle2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bhaskar
 */
public class FullBillings extends javax.swing.JFrame {

    

    /**
     * Creates new form FullBillings
     */
    public FullBillings() {
        initComponents();
        showdate();
        getsum();
//        billno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    @SuppressWarnings("unchecked")
    
    
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customername = new javax.swing.JTextField();
        customerquantity = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        service = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        foodmrp = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        foodname = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        foodtype = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Customer Name");
        jInternalFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Food Name");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 122, 121, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Food type");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 122, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mrp");
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 280, 33, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 330, 69, -1));
        jInternalFrame1.getContentPane().add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 80, 157, -1));
        jInternalFrame1.getContentPane().add(customerquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 327, 156, -1));

        Add.setBackground(new java.awt.Color(102, 255, 0));
        Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 0, 0));
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 51));

        table.setBackground(new java.awt.Color(255, 255, 0));
        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(255, 51, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Name", "Mrp", "Price"
            }
        ));
        jScrollPane2.setViewportView(table);

        jInternalFrame1.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Service charge(10%)");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date");
        jInternalFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 0, 73, 23));
        jInternalFrame1.getContentPane().add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 100, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Total");
        jInternalFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 70, 28));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 158, 28));

        foodmrp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jInternalFrame1.getContentPane().add(foodmrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 271, 147, 26));

        Print.setBackground(new java.awt.Color(255, 51, 51));
        Print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Print.setText("print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 80, 57));

        foodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodnameActionPerformed(evt);
            }
        });
        foodname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                foodnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                foodnameKeyTyped(evt);
            }
        });
        jInternalFrame1.getContentPane().add(foodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 118, 157, 28));

        jButton3.setText("Search");
        jInternalFrame1.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 157, -1, -1));

        foodtype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(foodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 152, 22));
        jInternalFrame1.getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 4, 159, 19));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 558, 70, 41));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/companyname/view/gautam.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jInternalFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 640));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 70, 20));
        jInternalFrame1.getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//public PageFormat getPageFormat(PrintJob pj){
//    PageFormat pf=new PageFormat();
//    Paper paper=pf.getPaper();
//    double middleHeight=8.0;
//    double headerHeight=2.0;
//    double footerHeight=2.0;
//    double width=convert_CM_TO_PPI(8);
//    double height=convert_CM_TO_PPI(headerHeight+middleHeight+footerHeight);
//    paper.setSize(width, height);
//    paper.setImageableArea(0, 10, width, height*convert_CM_TO_PPI(1));
//    pf.setOrientation(PageFormat.PORTRAIT);
//    pf.setPaper(paper);
//    return pf;
//    
//    
//}
//public class BillPrintable implements Printable{
//
//        
//        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) 
//                throws PrinterException {
//   int result= NO_SUCH_PAGE;
//   if(pageIndex==0){
//       Graphics2D g2d=(Graphics2D)graphics;
//       double width=pageFormat.getImageableWidth();
//       g2d.translate((int)pageFormat.getImageableX(),(int)pageFormat.getImageableY());
//       FontMetrics metrices=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
//       
//       
//       try{
//           int y=0;
//           int yShift=0;
//           int headerRectHeight=15;
//           int headerRectHeights=100;
////           jTable2.getTableHeader();
//           String tota=("total");
//           g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
//           g2d.drawString("-----------------------------", 12,y);y+=yShift;
//           g2d.drawString("Resturant bill receipt", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=headerRectHeights;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//            g2d.drawString("-----------------------------", 12,y);y+=yShift;
//           g2d.drawString(""+jTable2+"", 12,y);y+=yShift;
//            
//            
//             g2d.drawString("-----------------------------", 12,y);y+=yShift;
//             System.out.printf("sudeep");
//             g2d.drawString("Total amount:"+tota+"", 12,y);y+=yShift;
//       }catch(Exception e){
//          e.printStackTrace();
//       }
//       result=PAGE_EXISTS;
//   }
//   return result;
//            
//             //To change body of generated methods, choose Tools | Templates.
//        }
//    
//}
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
  
           
           DefaultTableModel model =(DefaultTableModel) table.getModel();
           String s2= customerquantity.getText();
                 String s1=foodmrp.getText();
                 int a=Integer.parseInt(s1);
                 int 
                 b=Integer.parseInt(s2);
                 int c=(a*b);
                 String e= Integer.toString(c);
                 price.setText(e);
                 model.addRow(new Object[]{customerquantity.getText(),foodname.getText(),foodmrp.getText(),price.getText()});
                 getsum();
                 
                 Bill bill =new Bill();
       //    bill.setBillno(Integer.parseInt(billno.getText()));
           bill.setCname(customername.getText());
           bill.setPrice(price.getText());
           bill.setDate(Date.getText());
           bill.setQuantity(customerquantity.getText());
           bill.setName(foodname.getText());
           bill.setMrp(foodmrp.getText());
           bill.setPrice(price.getText());
          
           FullBillingsDao dao=new FullBillingsDao();
          dao.savebill(bill); 
           
           
            
//           FullBillingsDao dao1= new FullBillingsDao();
//           dao1.saveSales(bill);
           
           System.out.println("data inserted");
           
                 //customername.setText("");
                foodname.setText("");
                 foodtype.setText("");
                 foodmrp.setText("");
                customerquantity.setText("");
                 
         

    }//GEN-LAST:event_AddActionPerformed
//public void billno(){
//    PreparedStatement ps=null;
//    try{
//        String sql="select count(*) from bill";
//        ps=Database.getConnection().prepareStatement(sql);
//        ResultSet rs=ps.executeQuery();
//        while(rs.next()){
//            int g=Integer.parseInt(rs.getString(1));
//            g=g+1;
//            billno.setText(String.valueOf(g));
//            
//        }
//    }catch(Exception e){
//      JOptionPane.showMessageDialog(null, e);
//    }
//    
//}
    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed

        PreparedStatement ps= null;
try{
    String sql="Delete from bill";
   
    ps=Database.getConnection().prepareStatement(sql);
   
    ps.executeQuery();
}catch(Exception e){
    
}



    // TODO add your handling code here:
    }//GEN-LAST:event_PrintActionPerformed
public void paint(Graphics g){
    g.drawString("total"+total.getText(),10,70);
}
    private void foodnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foodnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_foodnameKeyTyped

    private void foodnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foodnameKeyReleased

        //yo chai text ma kae type garda tae namm vako anusar aru details aune code:
        
        
        PreparedStatement ps=null;
        try{
            
    String sql="select * from add_foods where food_item=? ";
    ps=Database.getConnection().prepareStatement(sql);
    ps.setString(1,foodname.getText() );
    ResultSet rs=ps.executeQuery();
    if(rs.next()){
      String add1=rs.getString("food_type");
      foodtype.setText(add1);
      String add2=rs.getString("rate");
      foodmrp.setText(add2);
    }
    
            
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    
}
    // TODO add your handling code here:
    }//GEN-LAST:event_foodnameKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Employeemenuset m = new Employeemenuset();
m.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void foodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodnameActionPerformed
 public void getsum()
      {
          int sum=0;
          for(int i=0; i<table.getRowCount(); i++)
          {
              sum = sum + Integer.parseInt(table.getValueAt(i,3).toString());
              
          }
          double vat = sum*0.1;
          int vat1=(int)vat;
          String vat2=Integer.toString(vat1);
          service.setText(vat2);
          System.out.println(vat);
          double total1 = sum+vat;
          int total2 = (int)total1;
          System.out.println(total1);
          String total3=Integer.toString(total2);
          
          total.setText(total3);
      }
    
    
    
    
    public static  String DateFormat = "yyyy-MM-dd";
    public void showdate()
    {
      Calendar cal= Calendar.getInstance();
      SimpleDateFormat format = new SimpleDateFormat(DateFormat);
      Date.setText(format.format(cal.getTime()));

        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FullBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FullBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FullBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FullBillings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FullBillings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Date;
    private javax.swing.JButton Print;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField customerquantity;
    private javax.swing.JLabel foodmrp;
    private javax.swing.JTextField foodname;
    private javax.swing.JLabel foodtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField price;
    private javax.swing.JLabel service;
    private javax.swing.JTable table;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    protected static double convert_CM_TO_PPI(double cm) {
        return toPPI(cm*0.393600787); //To change body of generated methods, choose Tools | Templates.
    }
    protected static double toPPI(double inch) {
       return inch*72d; //To change body of generated methods, choose Tools | Templates.
    }
}
